### ISSUE TITLE
Вынести все числа в константы

### ISSUE THREAD

**Issue by coursar** [Khismatov-ilnaz/Cashback-3-cards#1]
https://github.com/Khismatov-ilnaz/Cashback-3-cards/blob/6ba702faeb9b9081c3c8c12c5f53c7b70cf878d1/app.js#L8-L27

**Comment by coursar** [comment]
Issue нужно закрывать сообщениями коммитов, а не вручную

**Comment by coursar** [comment]
Не исправлено:
https://github.com/Khismatov-ilnaz/Cashback-3-cards/blob/c3578ca7ce5a562ee25ae34709bf9a40c9657537/app.js#L2-L13

**Comment by Khismatov-ilnaz** [comment]
Fixed #1
